#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd -c /home/vini/.config/sxhkd/sxhkdrc &
picom &
# conky &

xrandr --output HDMI-1 --primary --mode 2560x1080 --rotate normal --output HDMI-0 --mode 2560x1080 --rotate right --left-of HDMI-1

bspc monitor HDMI-0 -d I II III
bspc monitor HDMI-1 -d IV V VI

~/.fehbg &

$HOME/.config/polybar/launch.sh

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.62
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc config automatic_scheme spiral

# bspc rule -a Chromium desktop='^2'
# bspc rule -a Gimp desktop='^8' state=floating follow=on
